import json
A='https://www.agenziaentrate.gov.it/portale/mini-guida-codice-fiscale-per-stranieri'; M='https://www.esteri.it/it/servizi-consolari-e-visti/italiani-all-estero/codice_fiscale/'
P='https://www.pmi.it/?p=362269'; V='https://telematici.agenziaentrate.gov.it/VerificaCF/IVerificaCfPf.jsp'; AR='https://arcom.agenziaentrate.gov.it/CitizenArCom/'
def a(u,t,it=True): return f'<a href="{u}" rel="noopener noreferrer"'+(' lang="it"' if it else '')+f'>{t}</a>'
def table(h,rows):
    th=''.join(f'<th>{x}</th>' for x in h); tr=''.join('<tr>'+''.join(f'<td>{c}</td>' for c in r)+'</tr>' for r in rows)
    return f'<div class="table-wrap"><table>\n<thead><tr>{th}</tr></thead>\n<tbody>\n{tr}\n</tbody></table></div>'
def ctable(h,pairs):
    rows=[[pairs[i][0],f'<code>{pairs[i][1]}</code>',pairs[i+1][0],f'<code>{pairs[i+1][1]}</code>'] for i in range(0,len(pairs),2)]
    return table(h,rows)
L={}
# ---------------- EN
L['en']=dict(slug='codice-fiscale-for-foreign-nationals',
 title='Codice Fiscale for Foreign Nationals | Codice Fiscale Pro',h1='Codice fiscale for foreign nationals and people born abroad',
 description='How the codice fiscale works if you are not Italian or were born abroad: the Z code, how EU and non-EU citizens get one, documents and limits.',
 indexDesc='The Z code for birthplace, how EU and non-EU citizens get a code, documents and limits of the calculation.',
 summary='People born abroad have a codice fiscale with the same layout as everyone else, but positions 12-15 hold the code of the country of birth, which always starts with Z (for example Z404 for the United States). EU citizens apply with form AA4/8 at an Agenzia delle Entrate office or an Italian consulate. For non-EU citizens the code is assigned by the immigration desk (Sportello Unico) or the police headquarters (Questura).',
 audience='foreign nationals who live, work or study in Italy, Italian citizens born abroad, and the employers, landlords and advisers who help them. It does not cover the tax code of companies.',
 faq=[('How do I calculate the codice fiscale if I was born abroad?','Calculate it like anyone else, but use the code of the country of birth instead of a municipality. It starts with Z, for example Z404 for the United States or Z114 for the United Kingdom.'),
  ('Can a foreign citizen get a codice fiscale?','Yes. EU citizens can apply with form AA4/8 at an Agenzia delle Entrate office. For non-EU citizens the immigration desk or the police headquarters assigns it, depending on the residence permit. Anyone legally staying in Italy without a code can apply at any Agenzia office.'),
  ('How do I write a name with accents or non-Latin letters?','Use the spelling on your identity document, such as the passport. Accents count as the base letter, while apostrophes, spaces and hyphens are ignored.'),
  ('What if my country of birth is not in the list?','The list holds current states. For states that no longer exist or changed name, ask the Agenzia delle Entrate which code was used.')],
 h=['How does the codice fiscale work for people born abroad?','How do you get a codice fiscale as a foreign national?','Which documents does the AA4/8 request need?','What happens if two people have the same data?','Where does the code arrive and how long is it valid?','How are names with accents, several surnames or non-Latin letters written?','Does the online calculation match the official code?','Sources'],
 p0='The layout is identical: surname, first name, year, month, day and sex, place, check letter. Only the place changes: it holds the code of the country of birth, written as a Z plus three digits. Example: John Brown, born in the United States on 3 November 1985, has <code>BRWJHN85S03Z404I</code> (an example person). Codes from the list of the Agenzia delle Entrate:',
 ct=['Country','Code','Country','Code'],pairs=[('United Kingdom','Z114'),('Ireland','Z116'),('United States','Z404'),('Canada','Z401'),('Australia','Z700'),('India','Z222')],
 p1=f'It depends on your situation, as the {a(A,"Agenzia delle Entrate brochure “Codice fiscale stranieri”")} (in Italian, 2023 edition) explains.',
 routes=['<strong>EU citizens</strong> who plan to stay in Italy submit form AA4/8 to a local Agenzia office, with a valid passport or an identity card valid for travel abroad. They can also ask at the Italian consulate in their country.','<strong>Non-EU citizens arriving in Italy:</strong> the immigration desk (Sportello Unico per l’Immigrazione) in each Prefecture assigns the code to people applying for a permit for employment or family reunification, and the police headquarters (Questura) for other permits. The immigration desk first gives a numeric provisional code, and the definitive one comes with the residence permit. With the Questura the definitive code comes at once.','<strong>International protection:</strong> the Questura or the border police assigns the code when the application is submitted.','<strong>Unaccompanied or irregular minors:</strong> the Agenzia assigns the code on the request of the local health authority (ASL) that must enrol the minor.','<strong>Ukrainian refugees:</strong> the Questura issues the definitive code when the application for a temporary permit is filed.','<strong>Legally resident in Italy without a code:</strong> apply at any Agenzia office with a signed form AA4/8 and a valid identity document. The request must be justified.'],
 p1b=f'Foreign nationals who do not live in Italy can, according to the {a(M,"Italian Foreign Ministry pages")} (in Italian), delegate a person to file the request at an Agenzia office in Italy. Italian citizens registered abroad (AIRE) go through the consulate.',
 p2='The accepted documents are a valid residence permit; a valid passport with a visa where required, or another document recognised by the Italian authorities; a proof of identity issued by the diplomatic or consular representation in Italy of the country of origin; or an Italian identity card. The form and its instructions are on the Agenzia delle Entrate site.',
 p3='If the data of two or more people produce the same code, the immigration desk or the Questura invites the person to an Agenzia office, which issues the definitive code after a check. A provisional code is valid in the meantime. This is the case explained in the guide <a href="{{g:cos-e-l-omocodia}}">what is omocodia</a>.',
 p4='According to the brochure, the code is sent by ordinary mail to the address of residence for residents, or to the tax domicile given in the request for non-residents. Only the code issued and certified by the Agenzia delle Entrate is valid, and it does not expire. EU citizens use the Italian health service with the European Health Insurance Card of their country of residence.',
 p5=f'Use the spelling on your identity document. Only letters of the alphabet count: accents, apostrophes, spaces and hyphens are ignored, and an accented letter counts as the base letter. With several surnames, they are read from left to right as one surname, as {a("https://www.avvocatoandreani.it/servizi/calcolo_codice_fiscale.php","this description of the rule")} (in Italian) puts it. If your name is spelled differently on two documents, the official code can differ from the calculated one.',
 p6=f'Often not for people born abroad, because name transliterations and country names can vary. {a(P,"Pmi.it")} (in Italian) names birth abroad among the cases where the result may not match. Use our <a href="{{{{p:home}}}}">calculator</a> as a starting point, then compare the code with your health card or the {a(V,"Agenzia delle Entrate verification service")}. Our list has 249 current states, so a state that has ceased to exist may be missing.',
 srcs=[(A,'Agenzia delle Entrate',': brochure “Codice fiscale stranieri”, routes, documents and delivery.'),(M,'Italian Foreign Ministry',': non-residents and Italians registered abroad.'),(P,'Pmi.it',': cases where the calculation may not match.')],lang=' (in Italian)',related=['come-si-calcola-il-codice-fiscale','codice-belfiore','come-trovare-il-proprio-codice-fiscale','errori-comuni-nel-codice-fiscale'])
# ---------------- DE
L['de']=dict(slug='codice-fiscale-fuer-auslaender',
 title='Codice Fiscale für Ausländer und im Ausland Geborene | Codice Fiscale Pro',h1='Codice Fiscale für Ausländer und im Ausland Geborene',
 description='So funktioniert der Codice Fiscale, wenn Sie nicht Italiener sind oder im Ausland geboren wurden: Z-Code, Weg für EU- und Nicht-EU-Bürger, Unterlagen.',
 indexDesc='Der Z-Code für den Geburtsort, der Weg für EU- und Nicht-EU-Bürger, Unterlagen und Grenzen der Berechnung.',
 summary='Wer im Ausland geboren wurde, hat einen Codice Fiscale mit demselben Aufbau wie alle anderen, aber die Stellen 12-15 enthalten den Code des Geburtsstaates, der immer mit Z beginnt (zum Beispiel Z112 für Deutschland). EU-Bürger beantragen ihn mit dem Formular AA4/8 bei einem Büro der Agenzia delle Entrate oder bei einem italienischen Konsulat. Bei Nicht-EU-Bürgern vergibt ihn der Einwanderungsschalter (Sportello Unico) oder die Polizeidirektion (Questura).',
 audience='Menschen aus Deutschland, Österreich, der Schweiz und anderen Ländern, die in Italien leben, arbeiten oder studieren oder dort eine Immobilie besitzen, sowie italienische Staatsbürger, die im Ausland geboren wurden. Die Steuernummer von Unternehmen behandelt der Ratgeber nicht.',
 faq=[('Wie berechne ich den Codice Fiscale, wenn ich im Ausland geboren bin?','Wie jeder andere, nur verwenden Sie statt einer Gemeinde den Code des Geburtsstaates. Er beginnt mit Z, zum Beispiel Z112 für Deutschland, Z102 für Österreich oder Z133 für die Schweiz.'),
  ('Können Ausländer einen Codice Fiscale bekommen?','Ja. EU-Bürger können ihn mit dem Formular AA4/8 bei einem Büro der Agenzia delle Entrate beantragen. Bei Nicht-EU-Bürgern vergibt ihn je nach Aufenthaltstitel der Einwanderungsschalter oder die Polizeidirektion. Wer sich rechtmäßig in Italien aufhält und keinen Code hat, kann ihn bei jedem Büro der Agenzia beantragen.'),
  ('Wie schreibe ich einen Namen mit Umlauten?','Verwenden Sie die Schreibweise im Ausweis, etwa im Reisepass. Buchstaben mit Akzent oder Umlaut zählen als Grundbuchstabe, Apostrophe, Leerzeichen und Bindestriche werden ignoriert.'),
  ('Gehört die Schweiz zu den EU-Staaten im Sinne des Verfahrens?','Die Broschüre der Agenzia unterscheidet zwischen EU- und Nicht-EU-Bürgern. Die Schweiz gehört nicht zur EU. Fragen Sie bei der Agenzia oder beim zuständigen Konsulat nach dem Weg, der für Sie gilt.')],
 h=['Wie funktioniert der Codice Fiscale für im Ausland Geborene?','Wie bekommt man als Ausländer einen Codice Fiscale?','Welche Unterlagen braucht der Antrag mit dem Formular AA4/8?','Was passiert, wenn zwei Personen dieselben Daten haben?','Wohin wird der Code geschickt und wie lange gilt er?','Wie schreibt man Namen mit Umlauten, mehreren Nachnamen oder nichtlateinischen Buchstaben?','Stimmt die Online-Berechnung mit dem amtlichen Code überein?','Quellen'],
 p0='Der Aufbau ist derselbe: Nachname, Vorname, Jahr, Monat, Tag und Geschlecht, Ort, Prüfbuchstabe. Nur der Ort ändert sich: Er enthält den Code des Geburtsstaates, geschrieben als Z mit drei Ziffern. Beispiel: Katharina Müller, geboren am 21. September 1988 in Deutschland, hat <code>MLLKHR88P61Z112O</code> (eine Beispielperson). Codes aus der Liste der Agenzia delle Entrate:',
 ct=['Staat','Code','Staat','Code'],pairs=[('Deutschland','Z112'),('Österreich','Z102'),('Schweiz','Z133'),('Liechtenstein','Z119'),('Luxemburg','Z120'),('Belgien','Z103')],
 p1=f'Es hängt von Ihrer Situation ab, wie die {a(A,"Broschüre „Codice fiscale stranieri“ der Agenzia delle Entrate")} (auf Italienisch, Ausgabe 2023) beschreibt.',
 routes=['<strong>EU-Bürger</strong>, die sich in Italien aufhalten wollen, reichen das Formular AA4/8 bei einem örtlichen Büro der Agenzia ein, mit gültigem Reisepass oder einem für Reisen ins Ausland gültigen Personalausweis. Sie können den Code auch beim italienischen Konsulat in ihrem Land beantragen.','<strong>Nicht-EU-Bürger, die nach Italien kommen:</strong> Der Einwanderungsschalter (Sportello Unico per l’Immigrazione) in jeder Präfektur vergibt den Code an Personen, die eine Aufenthaltserlaubnis für abhängige Beschäftigung oder Familiennachzug beantragen, die Polizeidirektion (Questura) bei anderen Aufenthaltstiteln. Der Einwanderungsschalter vergibt zunächst einen numerischen vorläufigen Code, den endgültigen gibt es mit der Aufenthaltserlaubnis. Bei der Questura kommt der endgültige Code sofort.','<strong>Internationaler Schutz:</strong> Die Questura oder die Grenzpolizei vergibt den Code bei Antragstellung.','<strong>Unbegleitete oder irreguläre Minderjährige:</strong> Die Agenzia vergibt den Code auf Antrag der Gesundheitsbehörde (ASL), die den Minderjährigen aufnehmen muss.','<strong>Geflüchtete aus der Ukraine:</strong> Die Questura stellt den endgültigen Code bei der Beantragung des vorübergehenden Aufenthaltstitels aus.','<strong>Rechtmäßig in Italien ohne Code:</strong> Beantragen Sie ihn bei jedem Büro der Agenzia mit dem unterschriebenen Formular AA4/8 und einem gültigen Ausweisdokument. Der Antrag muss begründet sein.'],
 p1b=f'Ausländer, die nicht in Italien leben, können nach den {a(M,"Seiten des italienischen Außenministeriums")} (auf Italienisch) eine Person bevollmächtigen, den Antrag bei einem Büro der Agenzia in Italien zu stellen. Italienische Staatsbürger, die im Ausland gemeldet sind (AIRE), wenden sich an das Konsulat.',
 p2='Anerkannt werden eine gültige Aufenthaltserlaubnis; ein gültiger Reisepass mit Visum, wo erforderlich, oder ein anderes von den italienischen Behörden anerkanntes Dokument; eine Identitätsbescheinigung der diplomatischen oder konsularischen Vertretung des Herkunftslandes in Italien; oder ein italienischer Personalausweis. Das Formular und die Ausfüllhinweise stehen auf der Website der Agenzia delle Entrate.',
 p3='Ergeben die Daten von zwei oder mehr Personen denselben Code, lädt der Einwanderungsschalter oder die Questura die Person in ein Büro der Agenzia ein, das nach einer Prüfung den endgültigen Code ausstellt. Bis dahin gilt ein vorläufiger Code. Das ist der Fall, den der Ratgeber <a href="{{g:cos-e-l-omocodia}}">Was ist Omocodia?</a> erklärt.',
 p4='Laut Broschüre wird der Code per gewöhnlicher Post geschickt: an die Wohnadresse bei Ansässigen, an das im Antrag angegebene steuerliche Domizil bei Nichtansässigen. Gültig ist nur der von der Agenzia delle Entrate ausgestellte und beglaubigte Code, und er läuft nicht ab. EU-Bürger nutzen das italienische Gesundheitssystem mit der Europäischen Krankenversicherungskarte ihres Wohnsitzlandes.',
 p5=f'Verwenden Sie die Schreibweise im Ausweis. Es zählen nur die Buchstaben des Alphabets: Akzente, Apostrophe, Leerzeichen und Bindestriche werden ignoriert, ein Buchstabe mit Akzent oder Umlaut zählt als Grundbuchstabe. Bei mehreren Nachnamen werden sie von links nach rechts wie ein einziger Nachname gelesen, so beschreibt es {a("https://www.avvocatoandreani.it/servizi/calcolo_codice_fiscale.php","diese Darstellung der Regel")} (auf Italienisch). Ist Ihr Name in zwei Dokumenten unterschiedlich geschrieben, kann der amtliche Code vom berechneten abweichen.',
 p6=f'Bei im Ausland Geborenen oft nicht, weil Namensumschriften und Staatsnamen variieren können. {a(P,"Pmi.it")} (auf Italienisch) nennt die Geburt im Ausland unter den Fällen, in denen das Ergebnis abweichen kann. Nutzen Sie unseren <a href="{{{{p:home}}}}">Rechner</a> als Ausgangspunkt und vergleichen Sie den Code dann mit Ihrer Gesundheitskarte oder dem {a(V,"Prüfdienst der Agenzia delle Entrate")}. Unsere Liste enthält 249 aktuelle Staaten, ein nicht mehr bestehender Staat kann daher fehlen.',
 srcs=[(A,'Agenzia delle Entrate',': Broschüre „Codice fiscale stranieri“, Wege, Unterlagen und Zustellung.'),(M,'Italienisches Außenministerium',': Nichtansässige und im Ausland gemeldete Italiener.'),(P,'Pmi.it',': Fälle, in denen die Berechnung abweichen kann.')],lang=' (Italienisch)',related=['come-si-calcola-il-codice-fiscale','codice-belfiore','come-trovare-il-proprio-codice-fiscale','errori-comuni-nel-codice-fiscale'])
json.dump(L,open('/tmp/gen/foreign_L.json','w'),ensure_ascii=False)
print('staged',list(L))
