exec(open('/tmp/gen/nb_change_common.py').read())
REL=['come-trovare-il-proprio-codice-fiscale','quando-puo-cambiare-il-codice-fiscale','codice-fiscale-per-cittadini-stranieri','come-si-calcola-il-codice-fiscale']
# ---------- EN
d=dict(slug='codice-fiscale-for-newborns',title='Codice Fiscale for Newborns: How It Works | Codice Fiscale Pro',h1='Codice fiscale for newborns: how it works',
 description='How a newborn gets a codice fiscale: assignment at birth, the one-year first card, the later card, and what to do if the code is missing or wrong.',
 indexDesc='Assignment at birth, the first card valid for one year, the later card and what to do if the code is missing.',
 summary='A newborn’s codice fiscale is assigned through the Comune when the birth is declared. The Agenzia delle Entrate then issues a first health card, valid for one year, and mails it to the address recorded in the tax registry. After the family registers the child with the local health authority (ASL), a new card with ordinary validity is produced. If the code was not communicated, parents can request it online.',
 audience='parents and relatives of a newborn who need the code for the paediatrician, nursery, child benefit or insurance forms before the card arrives. It also covers children born abroad to Italian parents.',
 faq=[('Do parents have to request the codice fiscale of a newborn?','Normally not. The Comune assigns it when the birth is declared. If the Comune did not communicate it, since 7 March 2025 parents can request it online in the reserved area of the Agenzia delle Entrate.'),
  ('How long is the first health card of a newborn valid?','One year. After the child is registered with the ASL, a new card with ordinary expiry is produced and mailed. Fisco Oggi reports the ordinary validity as six years.'),
  ('Can I calculate the code of my baby in advance?','You can calculate an estimate once you know the name, surname, date and place of birth. Before using it in a document, compare it with the code the Agenzia actually assigned, because only that one is valid.'),
  ('My child was born abroad to Italian parents. How do we get the code?','The Comune that transcribes the birth certificate assigns the code. Once the Comune has confirmed the AIRE registration, a registered parent can request the certificate through the consular portal Fast-it.')],
 related=REL)
secs=[('Who assigns the codice fiscale of a newborn?',[f'The Comune assigns it, through an IT system linked to the tax registry of the Agenzia delle Entrate, when the parents declare the birth. {a(INF.replace("codice-fiscale-verifica-dati-agenzia-delle-entrate","Codice-fiscale-cos-e-come-si-richiede"),"Informazione Fiscale")} (in Italian) confirms that for newborns the code is issued by the Comuni at the first registration in the population registry.']),
 ('When does the first card arrive, and how long does it last?',[f'According to the {a(AF,"Agenzia delle Entrate FAQ")} (in Italian), newborns who have been given a codice fiscale automatically receive a health card valid for one year. The card is mailed to the address recorded in the tax registry, normally the residence, as the {a(FF,"Agenzia press release of 7 March 2025")} (in Italian) states; for a newborn this is the address of the mother.','When the family registers the child with the ASL and chooses a paediatrician, the ASL sends the data to the health card system (Sistema TS) and a new card with ordinary expiry is produced, as the FAQ explains. Fisco Oggi, quoted by '+a(LP,"Lentepubblica.it")+' (in Italian), gives that validity as six years.']),
 ('What if the Comune did not communicate the code?',[f'Since 7 March 2025 a parent or a representative can request it online in the reserved area of the Agenzia delle Entrate website, without going to an office, and the certificate is made available online ({a(FF,"press release")}, in Italian). Form AA4/8 is the paper route to ask for a code that has not been assigned, according to the {a(AA,"Agenzia instructions for the form")} (in Italian).']),
 ('How can you calculate an estimate of the code?',['You need the surname and first name as written on the birth certificate, the date of birth, the sex and the municipality of birth. Enter them in the <a href="{{p:home}}">calculator</a>. With a compound name such as Anna Maria, the rules are in <a href="{{g:come-si-calcola-il-codice-fiscale}}">how the codice fiscale is calculated</a>.','The result is an estimate. The valid code is the one assigned, which can differ because of a different spelling of the name or, rarely, omocodia.']),
 ('What if the data of the child is wrong?',[f'Contact the Comune of residence or an Agenzia delle Entrate office with a valid identity document, as {a(LP2,"Lentepubblica.it")} (in Italian) indicates. The Agenzia instructions say that form AA4/8 is also used to communicate changes of personal data for someone who already has a code. After the correction, give the updated code to the paediatrician, the ASL and the school. See <a href="{{g:quando-puo-cambiare-il-codice-fiscale}}">when the codice fiscale can change</a>.']),
 ('What if the child was born abroad?',[f'For Italian minors born and resident abroad, the code is assigned by the Comune responsible for transcribing the birth certificate, which also leads to the AIRE registration. Only when the Comune has confirmed the AIRE registration can the certificate be requested through the consular portal Fast-it, as the {a(STO,"consular page of the Italian consulate in Stuttgart")} (in Italian) explains. Other consulates publish the same procedure for their district.','If the child is not an Italian citizen, see <a href="{{g:codice-fiscale-per-cittadini-stranieri}}">codice fiscale for foreign nationals</a>.'])]
srcs=[(AF,'Agenzia delle Entrate',': FAQ on the codice fiscale, first health card of newborns and omocodia.'),(AA,'Agenzia delle Entrate',': instructions for form AA4/8.'),(FF,'Fiscal Focus',': press release of 7 March 2025, online request for newborns.'),(LP,'Lentepubblica.it',': first and later health card, citing Fisco Oggi.'),(STO,'Italian Consulate in Stuttgart',': children born and resident abroad.')]
write('en','codice-fiscale-per-neonati',d,body(secs,srcs,'Sources',' (in Italian)',False))
# ---------- DE
d=dict(slug='codice-fiscale-fuer-neugeborene',title='Codice Fiscale für Neugeborene: So funktioniert es | Codice Fiscale Pro',h1='Codice Fiscale für Neugeborene: So funktioniert es',
 description='Wie ein Neugeborenes den Codice Fiscale bekommt: Vergabe bei der Geburt, erste Karte für ein Jahr, Folgekarte und was bei fehlendem Code zu tun ist.',
 indexDesc='Vergabe bei der Geburt, die erste Karte für ein Jahr, die Folgekarte und was bei fehlendem Code zu tun ist.',
 summary='Der Codice Fiscale eines Neugeborenen wird über die Gemeinde (Comune) vergeben, wenn die Geburt angezeigt wird. Die Agenzia delle Entrate stellt dann eine erste Gesundheitskarte mit einem Jahr Gültigkeit aus und schickt sie an die im Steuerregister erfasste Adresse. Nach der Anmeldung des Kindes bei der örtlichen Gesundheitsbehörde (ASL) wird eine neue Karte mit normaler Laufzeit erstellt. Wurde der Code nicht übermittelt, können Eltern ihn online anfordern.',
 audience='Eltern und Angehörige eines Neugeborenen, die den Code für Kinderarzt, Krippe, Kindergeld oder Versicherungsformulare brauchen, bevor die Karte ankommt. Der Ratgeber behandelt auch im Ausland geborene Kinder italienischer Eltern.',
 faq=[('Müssen Eltern den Codice Fiscale eines Neugeborenen beantragen?','In der Regel nicht. Die Gemeinde vergibt ihn bei der Geburtsanzeige. Hat die Gemeinde ihn nicht übermittelt, können Eltern ihn seit dem 7. März 2025 online im geschützten Bereich der Agenzia delle Entrate anfordern.'),
  ('Wie lange gilt die erste Gesundheitskarte eines Neugeborenen?','Ein Jahr. Nach der Anmeldung bei der ASL wird eine neue Karte mit normaler Laufzeit erstellt und verschickt. Fisco Oggi nennt als normale Laufzeit sechs Jahre.'),
  ('Kann ich den Code meines Babys vorab berechnen?','Sie können eine Schätzung berechnen, sobald Sie Vorname, Nachname, Geburtsdatum und Geburtsort kennen. Vergleichen Sie sie vor der Verwendung in einem Dokument mit dem tatsächlich vergebenen Code, denn nur dieser gilt.'),
  ('Mein Kind wurde im Ausland als Kind italienischer Eltern geboren. Wie bekommen wir den Code?','Die Gemeinde, die die Geburtsurkunde überträgt, vergibt den Code. Sobald sie die Eintragung im AIRE bestätigt hat, kann ein eingetragener Elternteil die Bescheinigung über das Konsularportal Fast-it anfordern.')],
 related=REL)
secs=[('Wer vergibt den Codice Fiscale eines Neugeborenen?',[f'Die Gemeinde vergibt ihn über ein IT-System, das mit dem Steuerregister der Agenzia delle Entrate verbunden ist, wenn die Eltern die Geburt anzeigen. {a("https://www.informazionefiscale.it/Codice-fiscale-cos-e-come-si-richiede","Informazione Fiscale")} (auf Italienisch) bestätigt, dass bei Neugeborenen die Gemeinden den Code bei der ersten Eintragung ins Melderegister vergeben.']),
 ('Wann kommt die erste Karte an und wie lange gilt sie?',[f'Laut den {a(AF,"FAQ der Agenzia delle Entrate")} (auf Italienisch) erhalten Neugeborene, denen ein Codice Fiscale zugewiesen wurde, automatisch eine Gesundheitskarte mit einem Jahr Gültigkeit. Die Karte wird an die im Steuerregister erfasste Adresse geschickt, normalerweise die Wohnadresse, wie die {a(FF,"Mitteilung der Agenzia vom 7. März 2025")} (auf Italienisch) angibt; bei einem Neugeborenen ist das die Adresse der Mutter.','Wenn die Familie das Kind bei der ASL anmeldet und einen Kinderarzt wählt, übermittelt die ASL die Daten an das Gesundheitskartensystem (Sistema TS) und es wird eine neue Karte mit normaler Laufzeit erstellt, wie die FAQ erklärt. Fisco Oggi, zitiert von '+a(LP,"Lentepubblica.it")+' (auf Italienisch), nennt als Laufzeit sechs Jahre.']),
 ('Was tun, wenn die Gemeinde den Code nicht übermittelt hat?',[f'Seit dem 7. März 2025 kann ein Elternteil oder ein Vertreter den Code im geschützten Bereich der Website der Agenzia delle Entrate online anfordern, ohne ein Büro aufzusuchen, und die Bescheinigung wird online bereitgestellt ({a(FF,"Mitteilung")}, auf Italienisch). Das Formular AA4/8 ist der Papierweg, um einen noch nicht vergebenen Code zu beantragen, laut den {a(AA,"Hinweisen der Agenzia zum Formular")} (auf Italienisch).']),
 ('Wie berechnet man eine Schätzung des Codes?',['Sie brauchen Nachnamen und Vornamen wie in der Geburtsurkunde, Geburtsdatum, Geschlecht und Geburtsgemeinde. Geben Sie sie in den <a href="{{p:home}}">Rechner</a> ein. Bei einem zusammengesetzten Namen wie Anna Maria stehen die Regeln im Ratgeber <a href="{{g:come-si-calcola-il-codice-fiscale}}">Codice Fiscale berechnen</a>.','Das Ergebnis ist eine Schätzung. Gültig ist der vergebene Code, der wegen einer anderen Schreibweise des Namens oder, selten, wegen Omocodia abweichen kann.']),
 ('Was tun, wenn die Daten des Kindes falsch sind?',[f'Wenden Sie sich mit einem gültigen Ausweis an die Wohnsitzgemeinde oder an ein Büro der Agenzia delle Entrate, wie {a(LP2,"Lentepubblica.it")} (auf Italienisch) angibt. Nach den Hinweisen der Agenzia dient das Formular AA4/8 auch dazu, Änderungen der Personendaten mitzuteilen, wenn bereits ein Code vorhanden ist. Teilen Sie nach der Korrektur den neuen Code Kinderarzt, ASL und Schule mit. Siehe <a href="{{g:quando-puo-cambiare-il-codice-fiscale}}">Wann kann sich der Codice Fiscale ändern?</a>']),
 ('Und wenn das Kind im Ausland geboren wurde?',[f'Bei italienischen Minderjährigen, die im Ausland geboren sind und dort leben, vergibt die Gemeinde den Code, die die Geburtsurkunde überträgt und damit auch die Eintragung im AIRE veranlasst. Erst wenn die Gemeinde die AIRE-Eintragung bestätigt hat, kann die Bescheinigung über das Konsularportal Fast-it angefordert werden, wie die {a(STO,"Seite des italienischen Konsulats in Stuttgart")} (auf Italienisch) erklärt. Andere Konsulate veröffentlichen dasselbe Verfahren für ihren Bezirk.','Ist das Kind kein italienischer Staatsbürger, siehe <a href="{{g:codice-fiscale-per-cittadini-stranieri}}">Codice Fiscale für Ausländer</a>.'])]
srcs=[(AF,'Agenzia delle Entrate',': FAQ zum Codice Fiscale, erste Gesundheitskarte von Neugeborenen und Omocodia.'),(AA,'Agenzia delle Entrate',': Hinweise zum Formular AA4/8.'),(FF,'Fiscal Focus',': Mitteilung vom 7. März 2025, Online-Antrag für Neugeborene.'),(LP,'Lentepubblica.it',': erste und spätere Gesundheitskarte, nach Fisco Oggi.'),(STO,'Italienisches Konsulat in Stuttgart',': im Ausland geborene und lebende Kinder.')]
write('de','codice-fiscale-per-neonati',d,body(secs,srcs,'Quellen',' (Italienisch)',False))
print('en de ok')
