exec(open('/tmp/gen/rest_common.py').read())
RI=['cos-e-il-codice-fiscale','come-leggere-e-decodificare-un-codice-fiscale','cos-e-l-omocodia','verifica-formale-e-verifica-ufficiale']
RB=['come-si-calcola-il-codice-fiscale','codice-fiscale-per-cittadini-stranieri','errori-comuni-nel-codice-fiscale','come-leggere-e-decodificare-un-codice-fiscale']
RE=['come-si-calcola-il-codice-fiscale','codice-belfiore','verifica-formale-e-verifica-ufficiale','cos-e-l-omocodia']
L='es'; LANG=' (en italiano)'
d=dict(slug='que-es-el-codice-fiscale-inverso',title='Codice fiscale inverso: qué puede decirte un código | Codice Fiscale Pro',h1='Codice fiscale inverso: qué puede decirte un código',
 description='Codice fiscale inverso: lee sexo, fecha y lugar de nacimiento. Por qué no se recupera el nombre y su diferencia con la verificación oficial.',indexDesc='Qué datos revela un código y por qué no se recuperan nombre y apellido.',
 summary='El codice fiscale inverso lee un código existente y devuelve los datos que contiene: sexo, día y mes de nacimiento, las dos últimas cifras del año y el lugar de nacimiento. No devuelve nombre ni apellido, porque las seis primeras letras encajan con muchos nombres: RSS encaja con Rossi, Rosso y Ross, y MRA con Mario, Mauro y Maria.',
 audience='quien quiera saber qué dice un código, por ejemplo para comprobar un formulario rellenado o un dato de un expediente. No sirve para identificar a desconocidos, algo que el código no permite.',
 faq=[('¿El codice fiscale inverso revela nombre y apellido?','No. Las seis primeras letras salen de consonantes y vocales del apellido y del nombre, y nombres distintos dan las mismas letras. Se pueden formular hipótesis, no recuperar los datos.'),('¿Qué se puede leer con certeza?','El sexo, el día y el mes de nacimiento, las dos últimas cifras del año y el código del municipio o del Estado de nacimiento. Con la lista de municipios, el código da el nombre del lugar.'),('¿El codice fiscale inverso es oficial?','No. Lee la estructura del código. Para saber si un código existe y corresponde a una persona, usa el servicio de la Agenzia delle Entrate.'),('¿Es seguro escribir un codice fiscale en una web de descifrado?','Depende de la web. Prefiere herramientas que funcionen en el navegador sin enviar los datos, como esta, y evita escribir códigos ajenos sin motivo.')],related=RI,lang=LANG,sh='Fuentes')
d['secs']=[('¿Qué es el codice fiscale inverso?',[f'Es el cálculo que parte de un código y vuelve a los datos personales que lo produjeron: lo contrario del <a href="{{{{g:come-si-calcola-il-codice-fiscale}}}}">cálculo normal</a>. Quien lo busca suele querer la fecha de nacimiento, el sexo y el municipio de nacimiento.']),
 ('¿Qué datos da el codice fiscale inverso?',['Da con certeza el sexo, el día, el mes, las dos últimas cifras del año y el código del lugar de nacimiento, que la <a href="{{p:inverse}}">lista de municipios y Estados</a> convierte en nombre de lugar. También muestra si el código es una variante de omocodia.',tbl(['Dato','¿Se puede leer?','Nota'],[['Sexo','Sí','Un día superior a 40 indica una mujer'],['Día y mes de nacimiento','Sí','La letra del mes hay que traducirla'],['Año de nacimiento','En parte','Solo dos cifras, el siglo queda abierto'],['Lugar de nacimiento','Sí','Según el código Belfiore, si está en la lista'],['Apellido y nombre','No','Solo hipótesis']])]),
 ('¿Por qué no se pueden recuperar nombre y apellido?',[f'Las seis primeras letras usan consonantes y, si hace falta, vocales, de modo que muchos nombres dan el mismo resultado. Rossi, Rosso y Ross dan todos <code>RSS</code>. Mario, Mauro y Maria dan todos <code>MRA</code>. Algunas fuentes hablan de buenas probabilidades de adivinar el nombre ({a(LENTE,"Lentepubblica.it")}, en italiano), pero sigue siendo una conjetura, y con el apellido es más difícil.']),
 ('¿Cómo se usa el codice fiscale inverso?',['Se escribe el código en el descifrador y se lee el resultado, en tres pasos.',ol(['Abre el <a href="{{p:inverse}}">descifrador</a>.','Escribe los 16 caracteres, también con letras en lugar de algunas cifras.','Lee sexo, fecha, lugar y código Belfiore, y mira el resultado de la comprobación formal.']),'Si dos años encajan con las dos cifras, por ejemplo 2005 y 1905, la herramienta muestra ambos y tú eliges el plausible.']),
 ('¿El codice fiscale inverso es una verificación oficial?',[f'No. Descifrar es leer la estructura del código. No dice si el código se asignó, ni a quién. Para eso mira <a href="{{{{g:verifica-formale-e-verifica-ufficiale}}}}">verificación formal y oficial</a> y el {a(V,"servicio de la Agenzia delle Entrate")} (en italiano).']),
 ('¿Cómo proteger la privacidad al descifrar un código?',['Un codice fiscale es un dato personal. Nuestra herramienta lo procesa en tu navegador y no lo envía ni a un servidor ni a Google Analytics. En otras webs, comprueba cómo tratan los datos, y evita escribir códigos ajenos sin un motivo concreto.'])]
d['srcs']=[(LENTE,'Lentepubblica.it',': datos legibles y límites del cálculo inverso.'),(PMI,'Pmi.it',': reglas de las letras.')]
emit(L,'cos-e-il-codice-fiscale-inverso',d)
d=dict(slug='codigo-belfiore',title='Código Belfiore: qué es y cómo encontrarlo | Codice Fiscale Pro',h1='Código Belfiore: qué es y cómo encontrarlo',
 description='El código Belfiore indica el municipio o Estado de nacimiento en el codice fiscale: formato, ejemplos reales, municipios homónimos y cómo buscarlo.',indexDesc='El código del lugar de nacimiento para municipios y Estados, con ejemplos reales.',
 summary='El código Belfiore es el código de cuatro caracteres (una letra y tres cifras) que identifica, en las posiciones 12-15 de un codice fiscale, el municipio italiano o el Estado extranjero de nacimiento. Roma es H501 y Milán F205. Los Estados extranjeros empiezan por Z, por ejemplo Z131 para España y Z600 para Argentina. Se encuentra en la lista de municipios y Estados de la Agenzia delle Entrate.',
 audience='quien termine un cálculo a mano, desarrolladores que validan codici fiscali y quien no sepa qué código usar para un municipio con nombre repetido o para un Estado extranjero.',
 faq=[('¿El código Belfiore es lo mismo que el código catastral?','En el uso corriente sí: es el código catastral del municipio. Ojo con las listas que traen varias columnas de códigos. En la lista de la Agenzia delle Entrate que usamos, el código correcto está en la columna «Codice Nazionale».'),('¿El código Belfiore indica dónde vivo?','No. En el codice fiscale indica el municipio o el Estado de nacimiento, nunca la residencia.'),('¿Qué hago si mi municipio de nacimiento ya no existe?','Usa el código que tenía el municipio al nacer. Nuestra lista solo incluye municipios y Estados actuales, así que comprueba esos casos con el servicio de verificación de la Agenzia delle Entrate.'),('¿Por qué algunos municipios tienen el mismo nombre pero códigos distintos?','Son municipios diferentes en provincias diferentes. Castro existe en la provincia de Bérgamo con el código C337 y en la de Lecce con el código M261. Hay que elegir el correcto.')],related=RB,lang=LANG,sh='Fuentes')
d['secs']=[('¿Qué es el código Belfiore?',[f'Es el código que identifica un municipio italiano o un Estado extranjero en las posiciones 12 a 15 del codice fiscale, formado por una letra y tres cifras. En los municipios sigue la codificación catastral, y los Estados extranjeros llevan una Z seguida de tres cifras, como explica {a(MON,"Money.it")} (en italiano).']),
 ('¿Qué ejemplos hay de códigos Belfiore?',['Ejemplos de la lista de la Agenzia delle Entrate incluida en este sitio:',tbl(['Lugar','Código','Estado','Código'],[['Roma','<code>H501</code>','España','<code>Z131</code>'],['Milán','<code>F205</code>','Argentina','<code>Z600</code>'],['Nápoles','<code>F839</code>','Colombia','<code>Z604</code>'],['Turín','<code>L219</code>','México','<code>Z514</code>'],['Florencia','<code>D612</code>','Chile','<code>Z603</code>']])]),
 ('¿Cómo se encuentra el código Belfiore de un municipio o Estado?',[f'Lo más rápido es el campo de lugar de la <a href="{{{{p:home}}}}">calculadora</a>: escribe el nombre, también en español, elige el lugar y el código se rellena. La lista completa está en el {a(AR,"archivo de la Agenzia delle Entrate")} (en italiano). Nuestra lista tiene 7.894 municipios y 249 Estados extranjeros, actualizada a 21 de febrero de 2026.']),
 ('¿Qué hacer con los municipios que comparten nombre?',['Distínguelos por la provincia: son municipios distintos con códigos distintos. Nuestra lista tiene cinco nombres así.',hom('')]),
 ('¿Qué columna se usa en las listas con varios códigos?',['Un detalle que comprobamos en la exportación de la Agenzia delle Entrate: la columna «Codice Nazionale» contiene el código Belfiore (para Roma <code>H501</code>), mientras que la columna «Codice Catastale» contiene otro código (para Roma <code>M1AA</code>). El segundo da codici fiscali erróneos.']),
 ('¿Qué pasa si el municipio fue suprimido o cambió?',[f'El codice fiscale conserva el código que tenía el municipio al nacer. Nuestra lista solo tiene entradas actuales. Quien nació en un municipio suprimido, fusionado o cedido a otro Estado puede tener un código que el cálculo no conoce. En esos casos, el {a(N01,"servicio de verificación de la Agenzia")} (2014, en italiano) es la herramienta adecuada. Mira también <a href="{{{{g:verifica-formale-e-verifica-ufficiale}}}}">verificación formal y oficial</a>.'])]
d['srcs']=[(AR,'Agenzia delle Entrate',': archivo de municipios y Estados extranjeros.'),(MON,'Money.it',': estructura del código del lugar.'),(N01,'01net.it',': verificación para nacidos en municipios cedidos (2014).')]
emit(L,'codice-belfiore',d)
rows=[['Nombre y apellido intercambiados','<code>MRA</code> aparece antes de <code>RSS</code>','Las tres primeras letras son el apellido, las tres siguientes el nombre'],['Sin +40 en el día de una mujer','Día de 01 a 31 en una mujer','En las mujeres suma 40: el día 5 pasa a 45'],['Letra de mes equivocada','Letras como F, G, I, N, O, Q en la posición 9','Usa solo A, B, C, D, E, H, L, M, P, R, S, T'],['Residencia en vez de lugar de nacimiento','Código distinto del municipio de nacimiento','Usa siempre el lugar de nacimiento'],['Columna equivocada en la lista de municipios','Un código como <code>M1AA</code> en vez de <code>H501</code>','Usa «Codice Nazionale», no «Codice Catastale»'],['Municipio homónimo de otra provincia','Castro: <code>C337</code> (BG) o <code>M261</code> (LE)','Elige también la provincia'],['Apellido del cónyuge','Código distinto del de la tarjeta sanitaria','Usa el apellido de nacimiento'],['Apóstrofos, espacios y tildes mal tratados','O’Connor que no da <code>CNN</code>','Ignora apóstrofos, espacios y tildes; la ñ vale como n'],['O en vez de 0, o al revés','Letra de control O frente a la cifra 0 en campos numéricos','El carácter de control es siempre una letra'],['Omocodia ignorada','Letras en posiciones que normalmente son cifras','Mira la tarjeta sanitaria y lee <a href="{{g:cos-e-l-omocodia}}">qué es la omocodia</a>']]
d=dict(slug='errores-comunes-codice-fiscale',title='Errores comunes en el codice fiscale | Codice Fiscale Pro',h1='Errores comunes en el codice fiscale y cómo evitarlos',
 description='Los errores más frecuentes al calcular o escribir un codice fiscale: sexo, mes, lugar, apellido y omocodia, con una tabla de errores.',indexDesc='Los fallos más frecuentes en el cálculo a mano y en las herramientas en línea.',
 summary='Los errores más frecuentes son: olvidar el +40 en el día de las mujeres, intercambiar nombre y apellido, usar un código de lugar equivocado (por ejemplo la columna equivocada de la lista o un municipio homónimo de otra provincia), confundir la letra O con la cifra 0 e ignorar la omocodia. Una comprobación formal detecta los cuatro primeros.',
 audience='quien calcule un codice fiscale a mano, lo copie de un documento a un formulario o escriba software que lo genere. Para cada error, la guía muestra cómo detectarlo y corregirlo.',
 faq=[('¿Cuál es el error más común en el cálculo a mano?','Olvidar sumar 40 al día de nacimiento de las mujeres, o intercambiar nombre y apellido. Ambos se ven al releer los dos grupos de tres letras.'),('¿Por qué mi código calculado difiere del de mi tarjeta sanitaria?','Las causas habituales son una grafía distinta del nombre en los documentos, un lugar de nacimiento equivocado, el uso del apellido del cónyuge o un código con omocodia asignado por la Agenzia.'),('¿Qué letras no se usan nunca para el mes?','F, G, I, N, O, Q, U, V, W, X, Y y Z no aparecen nunca. Los meses solo usan A, B, C, D, E, H, L, M, P, R, S, T.'),('¿Cómo compruebo un código después de calcularlo?','Usa la comprobación formal para los errores de estructura y compara el código con tu tarjeta sanitaria. Para una comprobación oficial está el servicio de la Agenzia delle Entrate.')],related=RE,lang=LANG,sh='Fuentes')
d['secs']=[('¿Cuáles son los errores más comunes al calcular un codice fiscale?',['La tabla recoge los diez errores más frecuentes, con la forma de detectar cada uno. Los ejemplos usan el código de muestra <code>RSSMRA85T10H501O</code>.',tbl(['Error','Cómo detectarlo','Cómo evitarlo'],rows)]),
 ('¿Por qué mi código calculado difiere del de mi tarjeta sanitaria?',[f'Los motivos más frecuentes son la grafía de los datos y la omocodia. {a(PMI,"Pmi.it")} (en italiano) cita espacios, apóstrofos, nombres dobles, caracteres especiales y nacimiento en el extranjero entre las causas. Un código con letras donde deberían ir cifras es una variante de omocodia.']),
 ('¿Cómo se comprueba un código después de calcularlo?',['Compruébalo en tres pasos, del más rápido al más seguro.',ol(['Pásalo por la <a href="{{p:verify}}">comprobación</a>: detecta estructura, fecha y letra de control erróneas.','Léelo con el <a href="{{p:inverse}}">descifrador</a> para ver que sexo, fecha y lugar son los esperados.',f'Compáralo con tu tarjeta sanitaria o con el {a(V,"servicio de la Agenzia delle Entrate")} (en italiano).'])]),
 ('¿Qué errores detecta una comprobación formal y cuáles no?',['Detecta estructura errónea, mes o día imposibles y una letra de control equivocada. No detecta un lugar erróneo pero plausible, un nombre escrito de otra forma ni un código que nadie posee. Para eso hace falta un documento oficial. Mira <a href="{{g:verifica-formale-e-verifica-ufficiale}}">verificación formal y oficial</a>.'])]
d['srcs']=[(PMI,'Pmi.it',': errores y variantes en los datos.'),(AR,'Agenzia delle Entrate',': lista de municipios y Estados.')]
emit(L,'errori-comuni-nel-codice-fiscale',d)
print('es done')
