exec(open('/tmp/gen/rest_common.py').read())
RI=['cos-e-il-codice-fiscale','come-leggere-e-decodificare-un-codice-fiscale','cos-e-l-omocodia','verifica-formale-e-verifica-ufficiale']
RB=['come-si-calcola-il-codice-fiscale','codice-fiscale-per-cittadini-stranieri','errori-comuni-nel-codice-fiscale','come-leggere-e-decodificare-un-codice-fiscale']
RE=['come-si-calcola-il-codice-fiscale','codice-belfiore','verifica-formale-e-verifica-ufficiale','cos-e-l-omocodia']
# ============ EN
d=dict(slug='reverse-codice-fiscale',title='Reverse Codice Fiscale: What a Code Can Tell You | Codice Fiscale Pro',h1='Reverse codice fiscale: what a code can tell you',
 description='A reverse codice fiscale reads a code and gives sex, date and place of birth. Why it cannot give a name, and how it differs from official verification.',indexDesc='Which data a code reveals and why the name and surname cannot be recovered.',
 summary='The reverse codice fiscale reads an existing code and returns the data it holds: sex, day and month of birth, the last two digits of the year and the place of birth. It cannot return a name or surname, because the first six letters fit many names: RSS fits Rossi, Rosso and Ross, MRA fits Mario, Mauro and Maria.',
 audience='anyone who wants to know what a code says, for example to check a filled-in form or a record in a file. It does not identify unknown people, which a code does not allow.',
 faq=[('Does the reverse codice fiscale reveal name and surname?','No. The first six letters come from consonants and vowels of surname and first name, and different names give the same letters. You can form guesses, not recover the data.'),('What can be read with certainty?','Sex, day and month of birth, the last two digits of the year and the code of the municipality or country of birth. With the list of municipalities the code gives the name of the place.'),('Is a reverse codice fiscale official?','No. It reads the structure of the code. To know whether a code exists and matches a person, use the Agenzia delle Entrate service.'),('Is it safe to type a codice fiscale into a decoding site?','It depends on the site. Prefer tools that work in your browser without sending the data, like this one, and avoid entering other people’s codes without a reason.')],related=RI,lang=' (in Italian)',sh='Sources')
d['secs']=[('What is a reverse codice fiscale?',[f'It is the calculation that starts from a code and goes back to the personal data that produced it: the opposite of the <a href="{{{{g:come-si-calcola-il-codice-fiscale}}}}">normal calculation</a>. People who search for it usually want the date of birth, the sex and the municipality of birth.']),
 ('Which data does a reverse codice fiscale give?',['It gives with certainty the sex, the day, the month, the last two digits of the year and the code of the place of birth, which the <a href="{{p:inverse}}">list of municipalities and countries</a> turns into a place name. It also shows whether the code is an omocodia variant.',tbl(['Data','Can be read?','Note'],[['Sex','Yes','A day above 40 means a woman'],['Day and month of birth','Yes','The month letter has to be translated'],['Year of birth','Partly','Two digits only, the century stays open'],['Place of birth','Yes','From the Belfiore code, if it is in the list'],['Surname and first name','No','Only guesses']])]),
 ('Why can name and surname not be recovered?',[f'The first six letters use consonants and, when needed, vowels, so many names give the same result. Rossi, Rosso and Ross all give <code>RSS</code>. Mario, Mauro and Maria all give <code>MRA</code>. Some sources speak of good odds of guessing the first name ({a(LENTE,"Lentepubblica.it")}, in Italian), but it stays a guess, and for the surname it is harder.']),
 ('How do you use the reverse codice fiscale?',['You type the code in the decoder and read the result, in three steps.',ol(['Open the <a href="{{p:inverse}}">decoder</a>.','Type the 16 characters, even with letters in place of some digits.','Read sex, date, place and Belfiore code, and check the formal check result.']),'If two years fit the two digits, for example 2005 and 1905, the tool shows both and you choose the plausible one.']),
 ('Is a reverse codice fiscale an official verification?',[f'No. Decoding reads the structure of the code. It does not say whether the code was assigned, or to whom. For that see <a href="{{{{g:verifica-formale-e-verifica-ufficiale}}}}">formal check and official verification</a> and the {a(V,"Agenzia delle Entrate service")} (in Italian).']),
 ('How can you protect privacy when decoding a code?',['A codice fiscale is personal data. Our tool processes it in your browser and does not send it to a server or to Google Analytics. With other sites, check how they treat the data, and avoid entering other people’s codes without a concrete reason.'])]
d['srcs']=[(LENTE,'Lentepubblica.it',': data that can be read and limits of the reverse calculation.'),(PMI,'Pmi.it',': rules for the letters.')]
emit('en','cos-e-il-codice-fiscale-inverso',d)
d=dict(slug='belfiore-code',title='Belfiore Code: What It Is and How to Find It | Codice Fiscale Pro',h1='Belfiore code: what it is and how to find it',
 description='The Belfiore code marks the municipality or country of birth in a codice fiscale: format, real examples, same-name municipalities and how to look it up.',indexDesc='The place-of-birth code for municipalities and countries, with real examples.',
 summary='The Belfiore code is the four-character code (one letter and three digits) that identifies the Italian municipality or the foreign country of birth in positions 12-15 of a codice fiscale. Rome is H501 and Milan F205. Foreign countries start with Z, for example Z404 for the United States and Z114 for the United Kingdom. You find it in the Agenzia delle Entrate list of municipalities and countries.',
 audience='anyone completing a calculation by hand, developers who validate codici fiscali, and anyone unsure which code to use for a municipality with a repeated name or for a foreign country.',
 faq=[('Is the Belfiore code the same as the cadastral code?','In everyday use yes: it is the cadastral code of the municipality. Beware of lists with several code columns. In the Agenzia delle Entrate list we use, the right code is in the column "Codice Nazionale".'),('Does the Belfiore code show where I live?','No. In the codice fiscale it shows the municipality or country of birth, never the residence.'),('What if my municipality of birth no longer exists?','Use the code the municipality had at the time of birth. Our list holds current municipalities and countries only, so check such cases with the Agenzia delle Entrate verification service.'),('Why do some municipalities have the same name but different codes?','They are different municipalities in different provinces. Castro exists in the province of Bergamo with code C337 and in the province of Lecce with code M261. Pick the right one.')],related=RB,lang=' (in Italian)',sh='Sources')
d['secs']=[('What is the Belfiore code?',[f'It is the code that identifies an Italian municipality or a foreign country in positions 12 to 15 of the codice fiscale, made of one letter and three digits. For municipalities it follows the cadastral coding, and foreign countries use a Z followed by three digits, as {a(MON,"Money.it")} (in Italian) explains.']),
 ('What are some examples of Belfiore codes?',['Examples from the Agenzia delle Entrate list included on this site:',tbl(['Place','Code','Place','Code'],[['Rome','<code>H501</code>','United States','<code>Z404</code>'],['Milan','<code>F205</code>','United Kingdom','<code>Z114</code>'],['Naples','<code>F839</code>','Ireland','<code>Z116</code>'],['Turin','<code>L219</code>','Canada','<code>Z401</code>'],['Florence','<code>D612</code>','Germany','<code>Z112</code>']])]),
 ('How do you find the Belfiore code of a municipality or country?',[f'The quickest way is the place field of the <a href="{{{{p:home}}}}">calculator</a>: type the name, in English too, and choose the place, and the code is filled in. The full list is in the {a(AR,"Agenzia delle Entrate archive")} (in Italian). Our list holds 7,894 municipalities and 249 foreign countries, current to 21 February 2026.']),
 ('What should you do with municipalities that share a name?',['Tell them apart by province: they are different municipalities with different codes. Our list has five such names.',hom('')]),
 ('Which column do you use in lists with several codes?',['One detail we checked on the Agenzia delle Entrate export: the column "Codice Nazionale" holds the Belfiore code (for Rome <code>H501</code>), while the column "Codice Catastale" holds a different code (for Rome <code>M1AA</code>). The second gives wrong codici fiscali.']),
 ('What if the municipality was suppressed or has changed?',[f'The codice fiscale keeps the code the municipality had at birth. Our list has current entries only. People born in a municipality that has been suppressed, merged or ceded to another state can have a code the calculation does not know. In those cases the {a(N01,"Agenzia verification service")} (2014, in Italian) is the right tool. See also <a href="{{{{g:verifica-formale-e-verifica-ufficiale}}}}">formal check and official verification</a>.'])]
d['srcs']=[(AR,'Agenzia delle Entrate',': archive of municipalities and foreign countries.'),(MON,'Money.it',': structure of the place code.'),(N01,'01net.it',': verification for people born in ceded municipalities (2014).')]
emit('en','codice-belfiore',d)
d=dict(slug='common-codice-fiscale-mistakes',title='Common Codice Fiscale Mistakes and How to Avoid Them | Codice Fiscale Pro',h1='Common codice fiscale mistakes and how to avoid them',
 description='The most frequent mistakes when calculating or typing a codice fiscale: sex, month, place, surname and omocodia, with a table of mistakes and checks.',indexDesc='The most frequent mistakes in hand calculation and online tools.',
 summary='The most frequent mistakes are forgetting the +40 on the day for women, swapping first name and surname, using a wrong place code (for example the wrong column of the list, or a municipality with the same name in another province), mixing up the letter O and the digit 0, and ignoring omocodia. A formal check catches the first four.',
 audience='anyone calculating a codice fiscale by hand, copying one from a document into a form, or writing software that generates it. For each mistake the guide shows how to spot it and how to fix it.',
 faq=[('What is the most common mistake in hand calculation?','Forgetting to add 40 to the day of birth for women, or swapping first name and surname. Both show up when you reread the two groups of three letters.'),('Why does my calculated code differ from my health card?','Common causes are a different spelling of the name on documents, a wrong place of birth, the use of a spouse’s surname, or an omocodia code assigned by the Agenzia.'),('Which letters are never used for the month?','F, G, I, N, O, Q, U, V, W, X, Y and Z never appear. Months only use A, B, C, D, E, H, L, M, P, R, S, T.'),('How do I check a code after calculating it?','Use the formal check to find structural errors and compare the code with your health card. For an official check use the Agenzia delle Entrate service.')],related=RE,lang=' (in Italian)',sh='Sources')
rows=[['First name and surname swapped','<code>MRA</code> appears before <code>RSS</code>','The first three letters are the surname, the next three the first name'],['No +40 on the day for a woman','Day 01 to 31 for a woman','For women add 40: day 5 becomes 45'],['Wrong month letter','Letters such as F, G, I, N, O, Q in position 9','Use only A, B, C, D, E, H, L, M, P, R, S, T'],['Residence instead of place of birth','Code differs from the municipality of birth','Always use the place of birth'],['Wrong column in the list of municipalities','A code like <code>M1AA</code> instead of <code>H501</code>','Use "Codice Nazionale", not "Codice Catastale"'],['Same-name municipality in another province','Castro: <code>C337</code> (BG) or <code>M261</code> (LE)','Choose the province too'],['Spouse’s surname used','Code differs from the health card','Use the surname at birth'],['Apostrophes and spaces counted as letters','O’Connor that does not give <code>CNN</code>','Ignore apostrophes, spaces and accents'],['O instead of 0, or the reverse','Check letter O against digit 0 in numeric fields','The check character is always a letter'],['Omocodia ignored','Letters in positions that are normally digits','Look at the health card and read <a href="{{g:cos-e-l-omocodia}}">what is omocodia</a>']]
d['secs']=[('What are the most common mistakes when calculating a codice fiscale?',['The table lists the ten most frequent mistakes with a way to spot each. Examples use the sample code <code>RSSMRA85T10H501O</code>.',tbl(['Mistake','How to spot it','How to avoid it'],rows)]),
 ('Why is my calculated code different from the one on my health card?',[f'The most frequent reasons are the spelling of the data and omocodia. {a(PMI,"Pmi.it")} (in Italian) lists spaces, apostrophes, double names, special characters and birth abroad among the causes. A code with letters where digits belong is an omocodia variant.']),
 ('How do you check a code after calculating it?',['Check it in three steps, from the quickest to the safest.',ol(['Run it through the <a href="{{p:verify}}">code check</a>: it spots wrong structure, date and check letter.',f'Read it with the <a href="{{{{p:inverse}}}}">decoder</a> to see that sex, date and place are the ones you expect.',f'Compare it with your health card or the {a(V,"Agenzia delle Entrate service")} (in Italian).'])]),
 ('Which mistakes does a formal check catch, and which not?',['It catches wrong structure, impossible month or day, and a wrong check letter. It does not catch a wrong but plausible place, a name spelled differently or a code that nobody owns. For those you need an official document. See <a href="{{g:verifica-formale-e-verifica-ufficiale}}">formal check and official verification</a>.'])]
d['srcs']=[(PMI,'Pmi.it',': mistakes and variants in the data.'),(AR,'Agenzia delle Entrate',': list of municipalities and countries.')]
emit('en','errori-comuni-nel-codice-fiscale',d)
print('en done')
