exec(open('/tmp/gen/rest_common.py').read())
RI=['cos-e-il-codice-fiscale','come-leggere-e-decodificare-un-codice-fiscale','cos-e-l-omocodia','verifica-formale-e-verifica-ufficiale']
RB=['come-si-calcola-il-codice-fiscale','codice-fiscale-per-cittadini-stranieri','errori-comuni-nel-codice-fiscale','come-leggere-e-decodificare-un-codice-fiscale']
RE=['come-si-calcola-il-codice-fiscale','codice-belfiore','verifica-formale-e-verifica-ufficiale','cos-e-l-omocodia']
L='fr'; LANG=' (en italien)'
d=dict(slug='codice-fiscale-inverse',title='Codice fiscale inverse : ce que révèle un code | Codice Fiscale Pro',h1='Codice fiscale inverse : ce que révèle un code',
 description='Codice fiscale inverse : lisez sexe, date et lieu de naissance. Pourquoi le nom reste introuvable, et la différence avec la vérification officielle.',indexDesc='Quelles données un code révèle et pourquoi le nom et le prénom ne se retrouvent pas.',
 summary='Le codice fiscale inverse lit un code existant et renvoie les données qu’il contient : sexe, jour et mois de naissance, deux derniers chiffres de l’année et lieu de naissance. Il ne renvoie ni nom ni prénom, car les six premières lettres conviennent à de nombreux noms : RSS convient à Rossi, Rosso et Ross, MRA à Mario, Mauro et Maria.',
 audience='toute personne qui veut savoir ce que dit un code, par exemple pour contrôler un formulaire rempli ou une fiche dans un dossier. Il ne permet pas d’identifier des inconnus, ce que le code n’autorise pas.',
 faq=[('Le codice fiscale inverse révèle-t-il nom et prénom ?','Non. Les six premières lettres viennent des consonnes et voyelles du nom et du prénom, et des noms différents donnent les mêmes lettres. On peut faire des hypothèses, pas retrouver les données.'),('Que peut-on lire avec certitude ?','Le sexe, le jour et le mois de naissance, les deux derniers chiffres de l’année et le code de la commune ou de l’État de naissance. Avec la liste des communes, le code donne le nom du lieu.'),('Le codice fiscale inverse est-il officiel ?','Non. Il lit la structure du code. Pour savoir si un code existe et correspond à une personne, utilisez le service de l’Agenzia delle Entrate.'),('Est-il sûr de saisir un codice fiscale sur un site de décodage ?','Cela dépend du site. Préférez les outils qui travaillent dans le navigateur sans envoyer les données, comme celui-ci, et évitez de saisir le code d’autrui sans raison.')],related=RI,lang=LANG,sh='Sources')
d['secs']=[('Qu’est-ce que le codice fiscale inverse ?',[f'C’est le calcul qui part d’un code et remonte aux données personnelles qui l’ont produit : l’inverse du <a href="{{{{g:come-si-calcola-il-codice-fiscale}}}}">calcul normal</a>. Ceux qui le cherchent veulent le plus souvent la date de naissance, le sexe et la commune de naissance.']),
 ('Quelles données le codice fiscale inverse donne-t-il ?',['Il donne avec certitude le sexe, le jour, le mois, les deux derniers chiffres de l’année et le code du lieu de naissance, que la <a href="{{p:inverse}}">liste des communes et États</a> transforme en nom de lieu. Il montre aussi si le code est une variante d’omocodia.',tbl(['Donnée','Lisible ?','Remarque'],[['Sexe','Oui','Un jour supérieur à 40 indique une femme'],['Jour et mois de naissance','Oui','La lettre du mois doit être traduite'],['Année de naissance','En partie','Deux chiffres seulement, le siècle reste ouvert'],['Lieu de naissance','Oui','D’après le code Belfiore, s’il figure dans la liste'],['Nom et prénom','Non','Seulement des hypothèses']])]),
 ('Pourquoi ne retrouve-t-on pas le nom et le prénom ?',[f'Les six premières lettres utilisent des consonnes et, au besoin, des voyelles, de sorte que de nombreux noms donnent le même résultat. Rossi, Rosso et Ross donnent tous <code>RSS</code>. Mario, Mauro et Maria donnent tous <code>MRA</code>. Certaines sources parlent de bonnes chances de deviner le prénom ({a(LENTE,"Lentepubblica.it")}, en italien), mais cela reste une conjecture, et c’est plus difficile pour le nom de famille.']),
 ('Comment utiliser le codice fiscale inverse ?',['On saisit le code dans le décodeur et on lit le résultat, en trois étapes.',ol(['Ouvrez le <a href="{{p:inverse}}">décodeur</a>.','Saisissez les 16 caractères, même avec des lettres à la place de certains chiffres.','Lisez sexe, date, lieu et code Belfiore, et regardez le résultat du contrôle formel.']),'Si deux années conviennent aux deux chiffres, par exemple 2005 et 1905, l’outil affiche les deux et vous choisissez la plausible.']),
 ('Le codice fiscale inverse est-il une vérification officielle ?',[f'Non. Décoder, c’est lire la structure du code. Cela ne dit pas si le code a été attribué, ni à qui. Voir <a href="{{{{g:verifica-formale-e-verifica-ufficiale}}}}">vérification formelle et officielle</a> et le {a(V,"service de l’Agenzia delle Entrate")} (en italien).']),
 ('Comment protéger sa vie privée en décodant un code ?',['Un codice fiscale est une donnée personnelle. Notre outil le traite dans votre navigateur et ne l’envoie ni à un serveur ni à Google Analytics. Sur d’autres sites, vérifiez comment les données sont traitées, et évitez de saisir le code d’autrui sans raison concrète.'])]
d['srcs']=[(LENTE,'Lentepubblica.it',' : données lisibles et limites du calcul inverse.'),(PMI,'Pmi.it',' : règles pour les lettres.')]
emit(L,'cos-e-il-codice-fiscale-inverso',d)
d=dict(slug='code-belfiore',title='Code Belfiore : définition et comment le trouver | Codice Fiscale Pro',h1='Code Belfiore : définition et comment le trouver',
 description='Le code Belfiore désigne la commune ou l’État de naissance dans le codice fiscale : format, exemples réels, communes homonymes et recherche.',indexDesc='Le code du lieu de naissance pour les communes et les États, avec des exemples réels.',
 summary='Le code Belfiore est le code de quatre caractères (une lettre et trois chiffres) qui désigne, aux positions 12-15 d’un codice fiscale, la commune italienne ou l’État étranger de naissance. Rome est H501, Milan F205. Les États étrangers commencent par Z, par exemple Z110 pour la France et Z133 pour la Suisse. On le trouve dans la liste des communes et États de l’Agenzia delle Entrate.',
 audience='toute personne qui termine un calcul à la main, les développeurs qui valident des codici fiscali et ceux qui ne savent pas quel code utiliser pour une commune au nom répété ou pour un État étranger.',
 faq=[('Le code Belfiore est-il le même que le code cadastral ?','Dans l’usage courant, oui : c’est le code cadastral de la commune. Attention aux listes avec plusieurs colonnes de codes. Dans la liste de l’Agenzia delle Entrate que nous utilisons, le bon code est dans la colonne « Codice Nazionale ».'),('Le code Belfiore indique-t-il où j’habite ?','Non. Dans le codice fiscale, il indique la commune ou l’État de naissance, jamais la résidence.'),('Que faire si ma commune de naissance n’existe plus ?','Utilisez le code qu’avait la commune à la naissance. Notre liste ne contient que les communes et États actuels : faites vérifier ces cas avec le service de vérification de l’Agenzia delle Entrate.'),('Pourquoi des communes ont-elles le même nom mais des codes différents ?','Ce sont des communes distinctes dans des provinces différentes. Castro existe dans la province de Bergame avec le code C337 et dans celle de Lecce avec le code M261. Il faut choisir la bonne.')],related=RB,lang=LANG,sh='Sources')
d['secs']=[('Qu’est-ce que le code Belfiore ?',[f'C’est le code qui désigne une commune italienne ou un État étranger aux positions 12 à 15 du codice fiscale, composé d’une lettre et de trois chiffres. Pour les communes, il suit le codage cadastral, et les États étrangers ont un Z suivi de trois chiffres, comme l’explique {a(MON,"Money.it")} (en italien).']),
 ('Quels sont quelques exemples de codes Belfiore ?',['Exemples tirés de la liste de l’Agenzia delle Entrate incluse dans ce site :',tbl(['Lieu','Code','État','Code'],[['Rome','<code>H501</code>','France','<code>Z110</code>'],['Milan','<code>F205</code>','Belgique','<code>Z103</code>'],['Naples','<code>F839</code>','Suisse','<code>Z133</code>'],['Turin','<code>L219</code>','Luxembourg','<code>Z120</code>'],['Florence','<code>D612</code>','Canada','<code>Z401</code>']])]),
 ('Comment trouve-t-on le code Belfiore d’une commune ou d’un État ?',[f'Le plus rapide est le champ du lieu du <a href="{{{{p:home}}}}">calculateur</a> : saisissez le nom, en français aussi, choisissez le lieu et le code est rempli. La liste complète est dans l’{a(AR,"archive de l’Agenzia delle Entrate")} (en italien). Notre liste compte 7 894 communes et 249 États étrangers, à jour au 21 février 2026.']),
 ('Que faire des communes qui ont le même nom ?',['Distinguez-les par la province : ce sont des communes différentes, avec des codes différents. Notre liste compte cinq noms dans ce cas.',hom('')]),
 ('Quelle colonne utiliser dans les listes à plusieurs codes ?',['Un détail vérifié sur l’export de l’Agenzia delle Entrate : la colonne « Codice Nazionale » contient le code Belfiore (pour Rome <code>H501</code>), alors que la colonne « Codice Catastale » contient un autre code (pour Rome <code>M1AA</code>). Le second donne des codici fiscali faux.']),
 ('Que se passe-t-il si la commune a été supprimée ou a changé ?',[f'Le codice fiscale garde le code qu’avait la commune à la naissance. Notre liste ne contient que des entrées actuelles. Une personne née dans une commune supprimée, fusionnée ou cédée à un autre État peut avoir un code que le calcul ne connaît pas. Dans ces cas, le {a(N01,"service de vérification de l’Agenzia")} (2014, en italien) est le bon outil. Voir aussi <a href="{{{{g:verifica-formale-e-verifica-ufficiale}}}}">vérification formelle et officielle</a>.'])]
d['srcs']=[(AR,'Agenzia delle Entrate',' : archive des communes et États étrangers.'),(MON,'Money.it',' : structure du code du lieu.'),(N01,'01net.it',' : vérification pour les personnes nées dans des communes cédées (2014).')]
emit(L,'codice-belfiore',d)
rows=[['Nom et prénom intervertis','<code>MRA</code> apparaît avant <code>RSS</code>','Les trois premières lettres sont le nom, les trois suivantes le prénom'],['Pas de +40 sur le jour d’une femme','Jour de 01 à 31 pour une femme','Pour les femmes, ajoutez 40 : le jour 5 devient 45'],['Mauvaise lettre de mois','Lettres comme F, G, I, N, O, Q en position 9','Utilisez seulement A, B, C, D, E, H, L, M, P, R, S, T'],['Résidence au lieu du lieu de naissance','Code différent de celui de la commune de naissance','Utilisez toujours le lieu de naissance'],['Mauvaise colonne dans la liste des communes','Un code comme <code>M1AA</code> au lieu de <code>H501</code>','Utilisez « Codice Nazionale », pas « Codice Catastale »'],['Commune homonyme d’une autre province','Castro : <code>C337</code> (BG) ou <code>M261</code> (LE)','Choisissez aussi la province'],['Nom du conjoint utilisé','Code différent de celui de la carte de santé','Utilisez le nom de naissance'],['Apostrophes, espaces et accents mal traités','O’Connor qui ne donne pas <code>CNN</code>','Ignorez apostrophes, espaces et accents'],['O au lieu de 0, ou l’inverse','Lettre de contrôle O contre chiffre 0 dans des champs numériques','Le caractère de contrôle est toujours une lettre'],['Omocodia ignorée','Lettres aux positions qui contiennent normalement des chiffres','Regardez la carte de santé et lisez <a href="{{g:cos-e-l-omocodia}}">qu’est-ce que l’omocodia</a>']]
d=dict(slug='erreurs-courantes-codice-fiscale',title='Erreurs courantes dans le codice fiscale | Codice Fiscale Pro',h1='Erreurs courantes dans le codice fiscale et comment les éviter',
 description='Les erreurs les plus fréquentes en calculant ou saisissant un codice fiscale : sexe, mois, lieu, nom, omocodia, avec un tableau des erreurs.',indexDesc='Les erreurs les plus fréquentes du calcul à la main et des outils en ligne.',
 summary='Les erreurs les plus fréquentes sont : oublier le +40 sur le jour des femmes, intervertir nom et prénom, utiliser un mauvais code de lieu (par exemple la mauvaise colonne de la liste ou une commune homonyme d’une autre province), confondre la lettre O et le chiffre 0, et ignorer l’omocodia. Un contrôle formel repère les quatre premières.',
 audience='toute personne qui calcule un codice fiscale à la main, le recopie d’un document dans un formulaire ou écrit un logiciel qui le génère. Pour chaque erreur, le guide montre comment la repérer et la corriger.',
 faq=[('Quelle est l’erreur la plus courante dans le calcul à la main ?','Oublier d’ajouter 40 au jour de naissance des femmes, ou intervertir nom et prénom. Les deux se voient en relisant les deux groupes de trois lettres.'),('Pourquoi mon code calculé diffère-t-il de ma carte de santé ?','Les causes courantes sont une graphie différente du nom sur les documents, un mauvais lieu de naissance, l’usage du nom du conjoint ou un code d’omocodia attribué par l’Agenzia.'),('Quelles lettres ne servent jamais pour le mois ?','F, G, I, N, O, Q, U, V, W, X, Y et Z n’apparaissent jamais. Les mois utilisent seulement A, B, C, D, E, H, L, M, P, R, S, T.'),('Comment contrôler un code après l’avoir calculé ?','Utilisez le contrôle formel pour les erreurs de structure et comparez le code avec votre carte de santé. Pour un contrôle officiel, il y a le service de l’Agenzia delle Entrate.')],related=RE,lang=LANG,sh='Sources')
d['secs']=[('Quelles sont les erreurs les plus courantes en calculant un codice fiscale ?',['Le tableau liste les dix erreurs les plus fréquentes, avec le moyen de les repérer. Les exemples utilisent le code d’exemple <code>RSSMRA85T10H501O</code>.',tbl(['Erreur','Comment la repérer','Comment l’éviter'],rows)]),
 ('Pourquoi mon code calculé diffère-t-il de celui de ma carte de santé ?',[f'Les raisons les plus fréquentes sont la graphie des données et l’omocodia. {a(PMI,"Pmi.it")} (en italien) cite espaces, apostrophes, prénoms doubles, caractères spéciaux et naissance à l’étranger parmi les causes. Un code avec des lettres là où il faut des chiffres est une variante d’omocodia.']),
 ('Comment contrôle-t-on un code après le calcul ?',['Contrôlez-le en trois étapes, de la plus rapide à la plus sûre.',ol(['Passez-le dans le <a href="{{p:verify}}">contrôle</a> : il repère une mauvaise structure, une mauvaise date et une mauvaise lettre de contrôle.','Lisez-le avec le <a href="{{p:inverse}}">décodeur</a> pour voir que sexe, date et lieu sont ceux attendus.',f'Comparez-le avec votre carte de santé ou le {a(V,"service de l’Agenzia delle Entrate")} (en italien).'])]),
 ('Quelles erreurs un contrôle formel repère-t-il, et lesquelles non ?',['Il repère une mauvaise structure, un mois ou un jour impossible et une lettre de contrôle fausse. Il ne repère pas un lieu faux mais plausible, un nom écrit autrement ou un code que personne ne possède. Pour cela, il faut un document officiel. Voir <a href="{{g:verifica-formale-e-verifica-ufficiale}}">vérification formelle et officielle</a>.'])]
d['srcs']=[(PMI,'Pmi.it',' : erreurs et variantes dans les données.'),(AR,'Agenzia delle Entrate',' : liste des communes et États.')]
emit(L,'errori-comuni-nel-codice-fiscale',d)
print('fr done')
