exec(open('/tmp/gen/rest_common.py').read())
RI=['cos-e-il-codice-fiscale','come-leggere-e-decodificare-un-codice-fiscale','cos-e-l-omocodia','verifica-formale-e-verifica-ufficiale']
RB=['come-si-calcola-il-codice-fiscale','codice-fiscale-per-cittadini-stranieri','errori-comuni-nel-codice-fiscale','come-leggere-e-decodificare-un-codice-fiscale']
RE=['come-si-calcola-il-codice-fiscale','codice-belfiore','verifica-formale-e-verifica-ufficiale','cos-e-l-omocodia']
# ================= DE
L='de'; LANG=' (Italienisch)'
d=dict(slug='codice-fiscale-rueckwaerts',title='Codice Fiscale rückwärts: Was der Code verrät | Codice Fiscale Pro',h1='Codice Fiscale rückwärts: Was ein Code verrät',
 description='Codice Fiscale rückwärts: Geschlecht, Geburtsdatum und Geburtsort auslesen. Warum kein Name herauskommt und was die amtliche Prüfung anders macht.',indexDesc='Welche Daten ein Code verrät und warum Vor- und Nachname nicht rekonstruierbar sind.',
 summary='Die Rückwärtssuche liest einen vorhandenen Codice Fiscale und liefert die enthaltenen Daten: Geschlecht, Tag und Monat der Geburt, die letzten zwei Ziffern des Jahres und den Geburtsort. Einen Vor- oder Nachnamen liefert sie nicht, denn die ersten sechs Buchstaben passen zu vielen Namen: RSS passt zu Rossi, Rosso und Ross, MRA zu Mario, Mauro und Maria.',
 audience='alle, die wissen wollen, was ein Code aussagt, etwa um ein ausgefülltes Formular oder einen Datensatz zu prüfen. Unbekannte Personen lassen sich damit nicht identifizieren, das erlaubt der Code nicht.',
 faq=[('Verrät die Rückwärtssuche Vor- und Nachname?','Nein. Die ersten sechs Buchstaben stammen aus Konsonanten und Vokalen von Nach- und Vorname, und verschiedene Namen ergeben dieselben Buchstaben. Man kann Vermutungen anstellen, aber die Daten nicht zurückgewinnen.'),('Was lässt sich sicher ablesen?','Geschlecht, Tag und Monat der Geburt, die letzten zwei Ziffern des Jahres und der Code der Gemeinde oder des Staates der Geburt. Mit der Gemeindeliste ergibt der Code den Ortsnamen.'),('Ist die Rückwärtssuche amtlich?','Nein. Sie liest die Struktur des Codes. Ob ein Code existiert und zu einer Person passt, klärt der Dienst der Agenzia delle Entrate.'),('Ist es sicher, einen Codice Fiscale in eine Entschlüsselungsseite einzugeben?','Das hängt von der Seite ab. Bevorzugen Sie Werkzeuge, die im Browser arbeiten und die Daten nicht senden, wie dieses, und geben Sie fremde Codes nicht ohne Grund ein.')],related=RI,lang=LANG,sh='Quellen')
d['secs']=[('Was ist die Rückwärtssuche beim Codice Fiscale?',[f'Es ist die Berechnung, die von einem Code ausgeht und zu den Personendaten zurückführt, aus denen er entstand: das Gegenteil der <a href="{{{{g:come-si-calcola-il-codice-fiscale}}}}">normalen Berechnung</a>. Wer danach sucht, möchte meist Geburtsdatum, Geschlecht und Geburtsgemeinde wissen.']),
 ('Welche Daten liefert die Rückwärtssuche?',['Sicher liefert sie Geschlecht, Tag, Monat, die letzten zwei Ziffern des Jahres und den Code des Geburtsortes, den die <a href="{{p:inverse}}">Liste der Gemeinden und Staaten</a> in einen Ortsnamen übersetzt. Sie zeigt auch, ob der Code eine Omocodia-Variante ist.',tbl(['Angabe','Ablesbar?','Hinweis'],[['Geschlecht','Ja','Ein Tag über 40 bedeutet Frau'],['Tag und Monat der Geburt','Ja','Der Monatsbuchstabe muss übersetzt werden'],['Geburtsjahr','Teilweise','Nur zwei Ziffern, das Jahrhundert bleibt offen'],['Geburtsort','Ja','Aus dem Belfiore-Code, wenn er in der Liste steht'],['Nach- und Vorname','Nein','Nur Vermutungen']])]),
 ('Warum lassen sich Vor- und Nachname nicht zurückgewinnen?',[f'Die ersten sechs Buchstaben nutzen Konsonanten und, wenn nötig, Vokale, sodass viele Namen dasselbe Ergebnis liefern. Rossi, Rosso und Ross ergeben alle <code>RSS</code>. Mario, Mauro und Maria ergeben alle <code>MRA</code>. Manche Quellen sprechen von guten Chancen, den Vornamen zu erraten ({a(LENTE,"Lentepubblica.it")}, auf Italienisch), es bleibt aber eine Vermutung, und beim Nachnamen ist es schwieriger.']),
 ('Wie nutzt man die Rückwärtssuche?',['Sie geben den Code im Decoder ein und lesen das Ergebnis, in drei Schritten.',ol(['Öffnen Sie den <a href="{{p:inverse}}">Decoder</a>.','Geben Sie die 16 Zeichen ein, auch mit Buchstaben anstelle einiger Ziffern.','Lesen Sie Geschlecht, Datum, Ort und Belfiore-Code und beachten Sie das Ergebnis der formalen Prüfung.']),'Passen zwei Jahre zu den zwei Ziffern, etwa 2005 und 1905, zeigt das Werkzeug beide, und Sie wählen das plausible.']),
 ('Ist die Rückwärtssuche eine amtliche Prüfung?',[f'Nein. Das Entschlüsseln liest die Struktur des Codes. Es sagt nicht, ob der Code vergeben wurde und an wen. Dazu siehe <a href="{{{{g:verifica-formale-e-verifica-ufficiale}}}}">Formale und amtliche Prüfung</a> und den {a(V,"Dienst der Agenzia delle Entrate")} (auf Italienisch).']),
 ('Wie schützt man die Privatsphäre beim Entschlüsseln?',['Ein Codice Fiscale ist ein personenbezogenes Datum. Unser Werkzeug verarbeitet ihn in Ihrem Browser und sendet ihn weder an einen Server noch an Google Analytics. Prüfen Sie bei anderen Seiten, wie sie die Daten behandeln, und geben Sie fremde Codes nicht ohne konkreten Grund ein.'])]
d['srcs']=[(LENTE,'Lentepubblica.it',': ablesbare Daten und Grenzen der Rückwärtsberechnung.'),(PMI,'Pmi.it',': Regeln für die Buchstaben.')]
emit(L,'cos-e-il-codice-fiscale-inverso',d)
d=dict(slug='belfiore-code-finden',title='Belfiore-Code: Was er ist und wie Sie ihn finden | Codice Fiscale Pro',h1='Belfiore-Code: Was er ist und wie Sie ihn finden',
 description='Der Belfiore-Code bezeichnet im Codice Fiscale Geburtsgemeinde oder Geburtsstaat: Format, echte Beispiele, gleichnamige Gemeinden, Nachschlagen.',indexDesc='Der Code des Geburtsortes für Gemeinden und Staaten, mit echten Beispielen.',
 summary='Der Belfiore-Code ist der vierstellige Code (ein Buchstabe und drei Ziffern), der an den Stellen 12-15 eines Codice Fiscale die italienische Gemeinde oder den ausländischen Geburtsstaat bezeichnet. Rom ist H501, Mailand F205. Ausländische Staaten beginnen mit Z, zum Beispiel Z112 für Deutschland und Z102 für Österreich. Sie finden ihn in der Liste der Gemeinden und Staaten der Agenzia delle Entrate.',
 audience='alle, die eine Berechnung von Hand abschließen, Entwickler, die Codici Fiscali validieren, und alle, die unsicher sind, welcher Code für eine Gemeinde mit wiederholtem Namen oder für einen ausländischen Staat gilt.',
 faq=[('Ist der Belfiore-Code dasselbe wie der Katastercode?','Im Alltag ja: Es ist der Katastercode der Gemeinde. Vorsicht bei Listen mit mehreren Codespalten. In der von uns genutzten Liste der Agenzia delle Entrate steht der richtige Code in der Spalte „Codice Nazionale“.'),('Zeigt der Belfiore-Code meinen Wohnort?','Nein. Im Codice Fiscale zeigt er die Geburtsgemeinde oder den Geburtsstaat, nie den Wohnsitz.'),('Was gilt, wenn meine Geburtsgemeinde nicht mehr existiert?','Verwenden Sie den Code, den die Gemeinde zur Zeit der Geburt hatte. Unsere Liste enthält nur aktuelle Gemeinden und Staaten, prüfen Sie solche Fälle daher mit dem Prüfdienst der Agenzia delle Entrate.'),('Warum haben manche Gemeinden denselben Namen, aber unterschiedliche Codes?','Es sind verschiedene Gemeinden in verschiedenen Provinzen. Castro gibt es in der Provinz Bergamo mit dem Code C337 und in der Provinz Lecce mit dem Code M261. Wählen Sie die richtige.')],related=RB,lang=LANG,sh='Quellen')
d['secs']=[('Was ist der Belfiore-Code?',[f'Es ist der Code, der an den Stellen 12 bis 15 des Codice Fiscale eine italienische Gemeinde oder einen ausländischen Staat bezeichnet, bestehend aus einem Buchstaben und drei Ziffern. Bei Gemeinden folgt er der Katastercodierung, ausländische Staaten haben ein Z mit drei Ziffern, wie {a(MON,"Money.it")} (auf Italienisch) erklärt.']),
 ('Welche Beispiele für Belfiore-Codes gibt es?',['Beispiele aus der in diese Website eingebundenen Liste der Agenzia delle Entrate:',tbl(['Ort','Code','Staat','Code'],[['Rom','<code>H501</code>','Deutschland','<code>Z112</code>'],['Mailand','<code>F205</code>','Österreich','<code>Z102</code>'],['Neapel','<code>F839</code>','Schweiz','<code>Z133</code>'],['Turin','<code>L219</code>','Liechtenstein','<code>Z119</code>'],['Florenz','<code>D612</code>','Luxemburg','<code>Z120</code>']])]),
 ('Wie findet man den Belfiore-Code einer Gemeinde oder eines Staates?',[f'Am schnellsten über das Ortsfeld des <a href="{{{{p:home}}}}">Rechners</a>: Name eingeben, auch auf Deutsch, den Ort wählen, und der Code wird eingetragen. Die vollständige Liste steht im {a(AR,"Archiv der Agenzia delle Entrate")} (auf Italienisch). Unsere Liste enthält 7.894 Gemeinden und 249 ausländische Staaten, Stand 21. Februar 2026.']),
 ('Was tun bei Gemeinden mit gleichem Namen?',['Unterscheiden Sie sie nach der Provinz: Es sind verschiedene Gemeinden mit verschiedenen Codes. In unserer Liste gibt es fünf solche Namen.',hom('')]),
 ('Welche Spalte nutzt man in Listen mit mehreren Codes?',['Ein Detail, das wir am Export der Agenzia delle Entrate geprüft haben: Die Spalte „Codice Nazionale“ enthält den Belfiore-Code (für Rom <code>H501</code>), die Spalte „Codice Catastale“ einen anderen Code (für Rom <code>M1AA</code>). Der zweite führt zu falschen Codici Fiscali.']),
 ('Was gilt bei aufgelösten oder geänderten Gemeinden?',[f'Der Codice Fiscale behält den Code, den die Gemeinde bei der Geburt hatte. Unsere Liste enthält nur aktuelle Einträge. Wer in einer aufgelösten, zusammengelegten oder an einen anderen Staat abgetretenen Gemeinde geboren wurde, kann einen Code haben, den die Berechnung nicht kennt. In diesen Fällen ist der {a(N01,"Prüfdienst der Agenzia")} (2014, auf Italienisch) das richtige Werkzeug. Siehe auch <a href="{{{{g:verifica-formale-e-verifica-ufficiale}}}}">Formale und amtliche Prüfung</a>.'])]
d['srcs']=[(AR,'Agenzia delle Entrate',': Archiv der Gemeinden und ausländischen Staaten.'),(MON,'Money.it',': Aufbau des Ortscodes.'),(N01,'01net.it',': Prüfung für in abgetretenen Gemeinden Geborene (2014).')]
emit(L,'codice-belfiore',d)
rows=[['Vor- und Nachname vertauscht','<code>MRA</code> steht vor <code>RSS</code>','Die ersten drei Buchstaben sind der Nachname, die nächsten drei der Vorname'],['Kein +40 beim Tag einer Frau','Tag 01 bis 31 bei einer Frau','Bei Frauen 40 addieren: Tag 5 wird 45'],['Falscher Monatsbuchstabe','Buchstaben wie F, G, I, N, O, Q an Stelle 9','Nur A, B, C, D, E, H, L, M, P, R, S, T verwenden'],['Wohnort statt Geburtsort','Code weicht von der Geburtsgemeinde ab','Immer den Geburtsort verwenden'],['Falsche Spalte in der Gemeindeliste','Ein Code wie <code>M1AA</code> statt <code>H501</code>','„Codice Nazionale“ verwenden, nicht „Codice Catastale“'],['Gleichnamige Gemeinde in anderer Provinz','Castro: <code>C337</code> (BG) oder <code>M261</code> (LE)','Auch die Provinz wählen'],['Name des Ehepartners verwendet','Code weicht von der Gesundheitskarte ab','Den Geburtsnamen verwenden'],['Apostrophe, Leerzeichen und Umlaute falsch behandelt','O’Connor ergibt nicht <code>CNN</code>','Apostrophe, Leerzeichen und Akzente ignorieren, Umlaute als Grundbuchstaben'],['O statt 0 oder umgekehrt','Prüfbuchstabe O gegen Ziffer 0 in Zahlenfeldern','Das Prüfzeichen ist immer ein Buchstabe'],['Omocodia übersehen','Buchstaben an Stellen, die sonst Ziffern enthalten','Gesundheitskarte ansehen und <a href="{{g:cos-e-l-omocodia}}">Was ist Omocodia?</a> lesen']]
d=dict(slug='haeufige-fehler-codice-fiscale',title='Häufige Fehler beim Codice Fiscale | Codice Fiscale Pro',h1='Häufige Fehler beim Codice Fiscale und wie Sie sie vermeiden',
 description='Die häufigsten Fehler beim Berechnen oder Eintippen eines Codice Fiscale: Geschlecht, Monat, Ort, Nachname, Omocodia, mit Fehlertabelle.',indexDesc='Die häufigsten Fehler bei der Handberechnung und in Online-Werkzeugen.',
 summary='Die häufigsten Fehler sind: das +40 beim Tag der Frauen vergessen, Vor- und Nachname vertauschen, einen falschen Ortscode verwenden (zum Beispiel die falsche Spalte der Liste oder eine gleichnamige Gemeinde in einer anderen Provinz), den Buchstaben O mit der Ziffer 0 verwechseln und Omocodia übersehen. Eine formale Prüfung findet die ersten vier.',
 audience='alle, die einen Codice Fiscale von Hand berechnen, aus einem Dokument in ein Formular übertragen oder Software schreiben, die ihn erzeugt. Zu jedem Fehler zeigt der Ratgeber, wie man ihn erkennt und behebt.',
 faq=[('Was ist der häufigste Fehler bei der Handberechnung?','Das +40 beim Tag der Frauen zu vergessen oder Vor- und Nachname zu vertauschen. Beides fällt auf, wenn man die zwei Dreiergruppen von Buchstaben noch einmal liest.'),('Warum weicht mein berechneter Code von der Gesundheitskarte ab?','Häufige Ursachen sind eine andere Schreibweise des Namens in den Dokumenten, ein falscher Geburtsort, der Name des Ehepartners oder ein von der Agenzia vergebener Omocodia-Code.'),('Welche Buchstaben werden nie für den Monat verwendet?','F, G, I, N, O, Q, U, V, W, X, Y und Z kommen nie vor. Monate nutzen nur A, B, C, D, E, H, L, M, P, R, S, T.'),('Wie prüfe ich einen Code nach der Berechnung?','Nutzen Sie die formale Prüfung für Strukturfehler und vergleichen Sie den Code mit der Gesundheitskarte. Für eine amtliche Prüfung gibt es den Dienst der Agenzia delle Entrate.')],related=RE,lang=LANG,sh='Quellen')
d['secs']=[('Was sind die häufigsten Fehler beim Berechnen eines Codice Fiscale?',['Die Tabelle nennt die zehn häufigsten Fehler und wie man sie erkennt. Die Beispiele nutzen den Beispielcode <code>RSSMRA85T10H501O</code>.',tbl(['Fehler','Woran man ihn erkennt','So vermeiden Sie ihn'],rows)]),
 ('Warum weicht mein berechneter Code von dem auf der Gesundheitskarte ab?',[f'Die häufigsten Gründe sind die Schreibweise der Daten und Omocodia. {a(PMI,"Pmi.it")} (auf Italienisch) nennt Leerzeichen, Apostrophe, Doppelnamen, Sonderzeichen und Geburt im Ausland unter den Ursachen. Ein Code mit Buchstaben, wo Ziffern stehen müssten, ist eine Omocodia-Variante.']),
 ('Wie prüft man einen Code nach der Berechnung?',['Prüfen Sie in drei Schritten, vom schnellsten zum sichersten.',ol(['Lassen Sie ihn durch die <a href="{{p:verify}}">Prüfung</a> laufen: Sie findet falschen Aufbau, falsches Datum und falschen Prüfbuchstaben.','Lesen Sie ihn mit dem <a href="{{p:inverse}}">Decoder</a>, um zu sehen, dass Geschlecht, Datum und Ort den Erwartungen entsprechen.',f'Vergleichen Sie ihn mit Ihrer Gesundheitskarte oder dem {a(V,"Dienst der Agenzia delle Entrate")} (auf Italienisch).'])]),
 ('Welche Fehler findet eine formale Prüfung und welche nicht?',['Sie findet falschen Aufbau, unmögliche Monate oder Tage und einen falschen Prüfbuchstaben. Nicht findet sie einen falschen, aber plausiblen Ort, einen anders geschriebenen Namen oder einen Code, den niemand besitzt. Dafür brauchen Sie ein amtliches Dokument. Siehe <a href="{{g:verifica-formale-e-verifica-ufficiale}}">Formale und amtliche Prüfung</a>.'])]
d['srcs']=[(PMI,'Pmi.it',': Fehler und Abweichungen bei den Daten.'),(AR,'Agenzia delle Entrate',': Liste der Gemeinden und Staaten.')]
emit(L,'errori-comuni-nel-codice-fiscale',d)
print('de done')
